use std::fs;
use std::path::{Path, PathBuf};

use crate::config;
use crate::error::{EverettError, Result};
use crate::session::{now, Session};
use crate::timefmt::strftime_local;

/// <vault>/<vault_dir>, or None when no vault is configured.
pub fn vault_folder() -> Option<PathBuf> {
    let vault = config::get("vault", Some("EVERETT_VAULT"), "");
    if vault.is_empty() {
        return None;
    }
    Some(crate::paths::expanduser(&vault).join(config::get("vault_dir", Some("EVERETT_VAULT_DIR"), "Everett")))
}

pub fn output_path() -> Result<PathBuf> {
    let folder = vault_folder().ok_or_else(|| {
        EverettError::new(
            2,
            "no vault configured: set EVERETT_VAULT, or add vault = \"~/path/to/notes\" to ~/.everett/config.toml",
        )
    })?;
    Ok(folder.join("Trunk.md"))
}

pub fn render(sessions: &[Session], at: Option<f64>) -> String {
    let stamp = strftime_local("%Y-%m-%d %H:%M", at.unwrap_or_else(now));
    let mut lines = vec![
        "---".to_string(),
        "title: Everett Trunk".to_string(),
        format!("generated: {}", stamp),
        "source: everett trunk".to_string(),
        "tags: [everett, generated]".to_string(),
        "---".to_string(),
        String::new(),
        "# Everett Trunk".to_string(),
        String::new(),
        format!("Live view of parallel sessions. Generated {}. Do not edit — regenerated by `everett trunk`.", stamp),
        String::new(),
        "| | Harness | Folder | Work | Last ask | Last active |".to_string(),
        "|---|---|---|---|---|---|".to_string(),
    ];
    for session in sessions {
        let dot = if session.running { '●' } else { '○' };
        let work = if !session.card.is_empty() {
            session.card.clone()
        } else if !session.title.is_empty() {
            session.title.clone()
        } else {
            session.first_user.chars().take(90).collect()
        };
        let work = work.replace('|', "/");
        let last: String = session.last_user.chars().take(90).collect::<String>().replace('|', "/");
        let when = strftime_local("%m-%d %H:%M", session.last_active);
        lines.push(format!("| {} | {} | `{}` | {} | {} | {} |", dot, session.harness, session.cwd, work, last, when));
    }
    lines.push(String::new());
    lines.push(String::new());
    lines.join("\n")
}

pub fn write(sessions: &[Session], path: Option<&Path>) -> Result<PathBuf> {
    let target = match path {
        Some(p) => p.to_path_buf(),
        None => output_path()?,
    };
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).map_err(|e| EverettError::new(2, e.to_string()))?;
    }
    fs::write(&target, render(sessions, None)).map_err(|e| EverettError::new(2, e.to_string()))?;
    Ok(target)
}
