from __future__ import annotations

import time
from pathlib import Path

from . import config
from .session import Session


class VaultNotConfiguredError(Exception):
    pass


def vault_folder() -> Path | None:
    """<vault>/<vault_dir>, or None when no vault is configured."""
    vault = config.get('vault', env='EVERETT_VAULT')
    if not vault:
        return None
    return Path(vault).expanduser() / config.get('vault_dir', env='EVERETT_VAULT_DIR', default='Everett')


def output_path() -> Path:
    folder = vault_folder()
    if folder is None:
        raise VaultNotConfiguredError(
            'no vault configured: set EVERETT_VAULT, or add vault = "~/path/to/notes" '
            'to ~/.everett/config.toml')
    return folder / 'Trunk.md'


def render(sessions: list[Session], now: float | None = None) -> str:
    stamp = time.strftime('%Y-%m-%d %H:%M', time.localtime(now or time.time()))
    lines = [
        '---', 'title: Everett Trunk', f'generated: {stamp}', 'source: everett trunk', 'tags: [everett, generated]', '---', '',
        '# Everett Trunk', '', f'Live view of parallel sessions. Generated {stamp}. Do not edit — regenerated by `everett trunk`.', '',
        '| | Harness | Folder | Work | Last ask | Last active |', '|---|---|---|---|---|---|',
    ]
    for session in sessions:
        dot = '●' if session.running else '○'
        work = (session.card or session.title or session.first_user[:90]).replace('|', '/')
        last = session.last_user[:90].replace('|', '/')
        when = time.strftime('%m-%d %H:%M', time.localtime(session.last_active))
        lines.append(f'| {dot} | {session.harness} | `{session.cwd}` | {work} | {last} | {when} |')
    lines += ['', '']
    return '\n'.join(lines)


def write(sessions: list[Session], path: Path | None = None) -> Path:
    target = path or output_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(sessions), encoding='utf-8')
    return target
